Url encode password
vanbalken/arris-tg2492lg pull request #28
Opened 2022-01-06 10:54 UTC by mathieupost

2022-01-06 13:22 UTC, vanbalken commented
@mathieupost Thanks for creating this pull request! This is valid issue. I compared your change with the javascript code used by the webpage of the router to make sure they do the same. The webpage also escapes special characters both for password and the username.

Do you use this library in your own code or as part of Home Assistant? If you use it with Home Assistant this will also need to be fixed on the 1.x version of this library and Home Assistant Core will need to be updated.

2022-01-06 13:28 UTC, mathieupost commented
My pleasure!

I was planning on using it in Home Assistant, but I was just trying out the library locally and found out that my password gave a 401. So I started debugging and found out that this was the issue ;)

I actually didn't know that there was integration with Home Assistant already! Can you point me to where I can find it? I'll look into fixing it there as well.

2022-01-06 13:36 UTC, vanbalken commented on arris_tg2492lg/connect_box.py
> +        async with self._websession.get(f"{self._hostname}/login?arg={arg}&_n={self._nonce}") as response:
What is your motivation to move the query parameters from `params` to the url?

2022-01-06 13:41 UTC, vanbalken commented
> My pleasure!
> 
> I was planning on using it in Home Assistant, but I was just trying out the library locally and found out that my password gave a 401. So I started debugging and found out that this was the issue ;)
> 
> I actually didn't know that there was integration with Home Assistant already! Can you point me to where I can find it? I'll look into fixing it there as well.

It is used in this integration: https://www.home-assistant.io/integrations/arris_tg2492lg/ I was planning on updating the integration so it can be configured in the UI but personal circumstances leave me with little time for that.

A quick fix would be to manually escape the special characters and than you can use the integration right away.

I will try to apply this fix to the 1.x version this weekend. Then we only need to bump the version of this library used in Home Assistant.

2022-01-06 13:43 UTC, mathieupost commented on arris_tg2492lg/connect_box.py
> +        async with self._websession.get(f"{self._hostname}/login?arg={arg}&_n={self._nonce}") as response:
For some reason the special characters in the base64 encoded string in the 'arg' param were encoded again (e.g. the trailing '=' was encoded as '%3D'), which would result in an internal server error from the router.

2022-01-06 13:45 UTC, mathieupost commented
Cool! I'll use the quick fix in the mean time. I'll look into it when I have time

2022-01-12 08:36 UTC, vanbalken requested changes
I fixed this for the 1.x version of this library which is used by Home Assisant: https://github.com/vanbalken/arris-tg2492lg/pull/29 The new version has been published on [PyPI](https://pypi.org/project/arris-tg2492lg/1.2.1/) and I only need to create a pullrequest to Home Assistant. I will try to do that this weekend.

I made some small changes in de the 1.x fix compared to this PR. If you could apply those here that would be great! I will add some unit tests later on.

2022-01-12 08:36 UTC, vanbalken commented on arris_tg2492lg/connect_box.py
> +        self._password = quote(password)
I would call `quote()` when creating the `arg_string` so the password stays unchanged here.

2022-01-12 08:36 UTC, vanbalken commented on arris_tg2492lg/connect_box.py
>          arg_string = f"{USERNAME}:{self._password}"
`arg_string = f"{quote(USERNAME)}:{quote(self._password)}"`

Although `USERNAME` (admin) doesn't need the be escaped I prefer to keep this in line with how the router portal works. If the username would ever be configurable I won't forget to escape it :)

2022-01-12 08:36 UTC, vanbalken commented on arris_tg2492lg/connect_box.py
> +        async with self._websession.get(f"{self._hostname}/login?arg={arg}&_n={self._nonce}") as response:
```
params = f"arg={arg}&_n={self.nonce}"
async with self._websession.get(f"{self._hostname}/login", params=params) as response:
```
It's a bit personal preference but if this works I would prefer it this way.

2024-01-12 12:56 UTC, vanbalken commented on arris_tg2492lg/connect_box.py
> +        async with self._websession.get(f"{self._hostname}/login?arg={arg}&_n={self._nonce}") as response:
The params are encoded by aiohttp when passed separately.

2024-01-12 13:00 UTC, vanbalken commented
Close pull request as changes have been incorporated in https://github.com/vanbalken/arris-tg2492lg/pull/41 which also includes unit tests.

Exactly 2 years later (what a coincidence :) ) and finally done :sweat_smile:

2024-01-12 13:00 UTC, closed without merging